In [7]:
import os
import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import f1_score
import lightgbm as lgb

#Feature importance
from sklearn.ensemble import RandomForestClassifier


#importing machine learning libraries
import tensorflow as tf
from tensorflow.keras.layers import Dense, LSTM, Input
from tensorflow.keras.models import Model
from tensorflow.keras.callbacks import EarlyStopping, ModelCheckpoint
import pickle



#Secondary imports
import pandas_profiling as pp

## Reading Datasets

In [3]:
train = pd.read_csv('train.csv')
test = pd.read_csv('test.csv')
sample = pd.read_csv('sample_submission.csv')

/usr/local/lib/python3.5/site-packages/IPython/core/interactiveshell.py:3058: DtypeWarning: Columns (746,835) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)
/usr/local/lib/python3.5/site-packages/IPython/core/interactiveshell.py:3058: DtypeWarning: Columns (700,731,740,752,761,789,811,820,829,841,850) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [4]:
train.shape

(17521, 2395)

In [5]:
test.shape

(20442, 2394)

In [13]:
train.drop(['Col747', 'Col836'], axis= 1, inplace=True)

In [6]:
train.head()

,Col1,Col2,Col3,Col4,Col5,Col6,Col7,Col8,Col9,Col10,...,Col2388,Col2389,Col2390,Col2391,Col2392,Col2393,Col2394,Col2395,Col2396,Col2397
0,RIGHGSN,1,1.086711e+04,8.648345e+03,1.576618e+04,2.890466e+04,5.273655e+03,2.346153e+04,1.285597e+04,2.871509e+04,...,0,1,0,1,214.0,214.0,68.0,22.0,22.0,7.0
1,RIMHI5ZGP,0,2.584312e+05,2.179633e+05,1.866287e+05,1.866287e+05,2.154519e+05,1.923615e+05,1.726538e+05,1.666974e+05,...,0,0,0,0,41.0,41.0,38.0,12.0,12.0,11.0
2,RIHOG1SZU,0,1.459355e+07,1.260060e+07,1.100315e+07,1.010315e+07,1.879882e+07,1.514035e+07,5.320778e+06,6.906324e+06,...,0,1,1,0,378.0,378.0,310.0,21.0,21.0,16.0
3,RIHOLMQWU,0,6.727043e+05,8.181116e+05,6.794893e+05,6.794893e+05,8.257254e+05,7.605803e+05,3.577134e+05,4.236612e+05,...,0,0,0,0,702.0,702.0,644.0,951.0,951.0,743.0
4,RIHO584ET,0,-1.218742e+06,-3.005361e+06,-1.666241e+05,-2.403574e+06,2.583183e+06,2.086546e+06,5.938358e+06,5.446532e+06,...,0,0,0,0,1305.0,1305.0,1211.0,2205.0,2205.0,1831.0

In [43]:
train.fillna(train.mean(), inplace=True)

In [47]:
rf = RandomForestClassifier()


#Creating features from training dataset
features1 = train[train.columns.difference(['Col2', 'Col1'])]


targets = train['Col2']

rf.fit(features1, targets) 

feature_importances = pd.DataFrame(rf.feature_importances_,
                                   index = train.columns.difference(['Col2', 'Col1']),
                                    columns=['importance']).sort_values('importance',ascending=False)
print(feature_importances)

/usr/local/lib/python3.5/site-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)

         importance
Col175     0.005661
Col440     0.005322
Col875     0.004959
Col621     0.004483
Col106     0.004087
Col240     0.003780
Col322     0.003463
Col431     0.003232
Col877     0.003143
Col178     0.003053
Col502     0.002990
Col180     0.002885
Col383     0.002882
Col23      0.002810
Col926     0.002701
Col874     0.002675
Col4       0.002647
Col915     0.002645
Col26      0.002597
Col243     0.002532
Col876     0.002498
Col922     0.002475
Col166     0.002473
Col43      0.002457
Col170     0.002410
Col24      0.002399
Col234     0.002394
Col16      0.002381
Col10      0.002379
Col185     0.002369
...             ...
Col2353    0.000000
Col2354    0.000000
Col2355    0.000000
Col2356    0.000000
Col2331    0.000000
Col58      0.000000
Col1559    0.000000
Col1251    0.000000
Col2293    0.000000
Col2294    0.000000
Col2295    0.000000
Col2297    0.000000
Col230     0.000000
Col1237    0.000000
Col2300    0.000000
Col1239    0.000000
Col2308    0.000000
Col1410    0.000000
Col1465    0.000000
Col2315    0.000000
Col2316    0.000000
Col2317    0.000000
Col577     0.000000
Col1555    0.000000
Col2320    0.000000
Col2322    0.000000
Col2323    0.000000
Col2324    0.000000
Col1250    0.000000
Col2225    0.000000

[2391 rows x 1 columns]

In [53]:
feature_importances.reset_index()

        index  importance
0      Col175    0.005661
1      Col440    0.005322
2      Col875    0.004959
3      Col621    0.004483
4      Col106    0.004087
5      Col240    0.003780
6      Col322    0.003463
7      Col431    0.003232
8      Col877    0.003143
9      Col178    0.003053
10     Col502    0.002990
11     Col180    0.002885
12     Col383    0.002882
13      Col23    0.002810
14     Col926    0.002701
15     Col874    0.002675
16       Col4    0.002647
17     Col915    0.002645
18      Col26    0.002597
19     Col243    0.002532
20     Col876    0.002498
21     Col922    0.002475
22     Col166    0.002473
23      Col43    0.002457
24     Col170    0.002410
25      Col24    0.002399
26     Col234    0.002394
27      Col16    0.002381
28      Col10    0.002379
29     Col185    0.002369
...       ...         ...
2361  Col2353    0.000000
2362  Col2354    0.000000
2363  Col2355    0.000000
2364  Col2356    0.000000
2365  Col2331    0.000000
2366    Col58    0.000000
2367  Col1559    0.000000
2368  Col1251    0.000000
2369  Col2293    0.000000
2370  Col2294    0.000000
2371  Col2295    0.000000
2372  Col2297    0.000000
2373   Col230    0.000000
2374  Col1237    0.000000
2375  Col2300    0.000000
2376  Col1239    0.000000
2377  Col2308    0.000000
2378  Col1410    0.000000
2379  Col1465    0.000000
2380  Col2315    0.000000
2381  Col2316    0.000000
2382  Col2317    0.000000
2383   Col577    0.000000
2384  Col1555    0.000000
2385  Col2320    0.000000
2386  Col2322    0.000000
2387  Col2323    0.000000
2388  Col2324    0.000000
2389  Col1250    0.000000
2390  Col2225    0.000000

[2391 rows x 2 columns]

In [55]:
feature_importances['importance'].values

array([0.0056607 , 0.0053217 , 0.00495867, ..., 0.        , 0.        ,
       0.        ])

In [67]:
sorted(feature_importances[feature_importances.importance > 0.002].reset_index()['index'].values.tolist(), key = lambda x: int(x[3:]))

['Col3',
 'Col4',
 'Col5',
 'Col6',
 'Col9',
 'Col10',
 'Col16',
 'Col23',
 'Col24',
 'Col26',
 'Col27',
 'Col43',
 'Col92',
 'Col93',
 'Col106',
 'Col161',
 'Col162',
 'Col163',
 'Col164',
 'Col166',
 'Col170',
 'Col175',
 'Col176',
 'Col177',
 'Col178',
 'Col180',
 'Col185',
 'Col186',
 'Col234',
 'Col240',
 'Col243',
 'Col302',
 'Col322',
 'Col358',
 'Col383',
 'Col418',
 'Col428',
 'Col431',
 'Col440',
 'Col461',
 'Col467',
 'Col502',
 'Col608',
 'Col615',
 'Col621',
 'Col652',
 'Col666',
 'Col713',
 'Col762',
 'Col873',
 'Col874',
 'Col875',
 'Col876',
 'Col877',
 'Col880',
 'Col907',
 'Col913',
 'Col915',
 'Col922',
 'Col926',
 'Col1454']

In [65]:
train_data = train[feature_importances[feature_importances.importance > 0.002].reset_index()['index'].values.tolist()]
test_data = test[feature_importances[feature_importances.importance > 0.002].reset_index()['index'].values.tolist()]

In [71]:
lgbb = lgb.LGBMClassifier()
lgbb.fit(train_data.values, train['Col2'].values)

LGBMClassifier(boosting_type='gbdt', class_weight=None, colsample_bytree=1.0,
               importance_type='split', learning_rate=0.1, max_depth=-1,
               min_child_samples=20, min_child_weight=0.001, min_split_gain=0.0,
               n_estimators=100, n_jobs=-1, num_leaves=31, objective=None,
               random_state=None, reg_alpha=0.0, reg_lambda=0.0, silent=True,
               subsample=1.0, subsample_for_bin=200000, subsample_freq=0)

In [72]:
result = lgbb.predict(test_data.values)

In [74]:
sample.head()

        Col1  Col2
0  RIGD58ZWD     0
1  RIH660YDS     1
2  RIH660Q96     0
3  RIYDO15W1     1

In [75]:
submission = pd.DataFrame()
submission['Col1'] = test['Col1']
submission['Col2'] = result

In [79]:
submission.to_csv('submission.csv', index=False)